### Data Preprocessing
Submitted By <br/>
Name: **Joan Jose M** <br/>
<hr/>

## Mounting Drive

In [1]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


---
## Importing Libraries
- library: ensemble of modules and classes with which you can perform actions
- eg. scikit learn contians all ML models
- syn: import library as shortcut (OR) import library.module as shortcut

In [2]:
# work with arrays
import numpy as np

# plot charts
import matplotlib.pyplot as plt

# import dataset & create various features
import pandas as pd

---
## Loading the Dataset
- Retail Company performing analysis on which client purchased one of their product
- rows corresponde one of customers of employee
- Columns present are:
1. Country: country where the customer lives
1. Age: age of customer
1. Salary: salary of customer
1. Purchased: whether they purchased the product or not?

In [3]:
# variable contain the dataset
dataset=pd.read_csv('/content/drive/MyDrive/Datasets/Data.csv')

In [4]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [23]:
dataset.shape

(10, 4)

- Missing values for 2 customers in column Age & salary

#### Features (independent variable)
- columns with which you predict the dependent variable
- usually the set of first columns


In [5]:
# feature variable matrix
X=dataset.iloc[:,:-1].values

- iloc: locates the indexes of rows/columns to be extracted
- syn: df.iloc[rows:,cols:]
- eg. iloc[:, :-1] -> all columns except the last column
- in python range it includes the lower bound and excludes the upper bound

In [6]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


#### Target
- dependent variable
- usually the last set of columns

In [7]:
# target
y=dataset.iloc[:,-1].values

In [8]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


---
## Data Preprocessing
- scikit learn contains many data preprocessing tools

In [9]:
dataset.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

### Taking care of missing value
- replace with median,average or frequent value

In [10]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')

In [11]:
imputer.fit(X[:, 1:3])

SimpleImputer()

- fit connects imputer to matrix of features
- i.e. look at missing values and aalso compute the average value of that particular column
- works with numerical values so select only columns with missing values present in it

In [12]:
X[:, 1:3]=imputer.transform(X[:, 1:3])

- transform: replacement of missing values
- return new updated feature of matrix X with 2 replacements i.e. salary,age
- update matrix of feature X

In [13]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


### Encoding Categorical Data
- ML model difficult to compute some correlations between fetures & outcome
- convert string into numbers
- encode the categorical column
- numerical order matters, no relationship between order

### One Hot Encoding
- creating binary vectors
- eg. Country & Purchased

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])],remainder='passthrough')
X=np.array(ct.fit_transform(X))

In [15]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding Dependent variable

In [16]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [17]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


### Splitting dataset into Training & Testing set
- apply feature scaling after splitting the dataset into training & testing set
- test set should be brand new set
- training set: train model on existing obs
- testing set: evaluate the performance of model on new obs

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [19]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [20]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [21]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [22]:
print(y_test)

[0 1]


### Feature Scaling
- Scaling all variables/features to make sure that they all take values in same scale
- get mean & std dev for test set, prevent information leakage

- Standardization: -3<X(stand)<+3
- Normalization: 0<X(norm)<1
- Normalization is recommended when you have normal distribution in most features
- Standardization works all the time, relevant feature scaling
- StandardScaler for Standardization

In [24]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])

- Need to apply standardization to dummy variables -> no need because it takes values between -3 & +3

In [25]:
X_test[:, 3:] = sc.fit_transform(X_test[:, 3:])

In [26]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [27]:
print(X_test)

[[0.0 1.0 0.0 -1.0 -1.0]
 [1.0 0.0 0.0 1.0 1.0]]


- Age & salary takes values between -2 & +2

---